import Head from 'next/head';
import Image from 'next/image';
import classNames from 'classnames';
import styles from '@/styles/Home.module.css';
import CardLink from '@/components/CardLink';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <div
          className={classNames(
            styles.description,
            'z-[2] w-full max-w-[1100px] font-mono text-[12.8px] [display:inherit] [align-items:inherit] [justify-content:inherit]',
          )}
        >
          <p
            className={classNames(
              'fixed flex w-full justify-center',
              'inset-0 bottom-auto m-0 items-center rounded-none px-4 pt-8 pb-[22.4px] backdrop-blur-xl',
            )}
          >
            Get started by editing&nbsp;
            <code className="font-bold">src/pages/index.tsx</code>
          </p>
          <div
            className={classNames(
              'fixed flex w-full justify-center',
              'pointer-events-none inset-0 top-auto z-[1] h-[200px] items-end p-8',
            )}
          >
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className="flex items-center justify-center gap-2 p-4"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div
          className={classNames(
            styles.center,
            'relative flex items-center justify-center pt-32 pb-24',
            'before:absolute before:left-1/2 before:blur-[45px] before:content-[""]',
            'before:-ml-[400px] before:h-[300px] before:w-[480px] before:transform-none before:rounded-full',
            'after:absolute after:left-1/2 after:blur-[45px] after:content-[""]',
            'after:-z-[1] after:h-[180px] after:w-60 after:[transform:translateZ(0)]',
          )}
        >
          <Image
            className={classNames(styles.logo, 'relative')}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div
            className={classNames(
              styles.thirteen,
              'relative ml-4 flex h-[75px] w-[75px] items-center justify-center overflow-hidden rounded-xl px-2.5 py-[25px] shadow-[0_2px_8px_-1px] shadow-black/10 [transform:translateZ(0)]',
              'before:absolute before:-z-[1] before:content-[""]',
              'before:h-[200%] before:w-[200%] before:animate-[6s_rotate_linear_infinite]',
              'after:absolute after:-z-[1] after:content-[""]',
              'after:inset-0 after:rounded-xl after:p-px',
            )}
          >
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div
          className={classNames(
            styles.grid,
            'mb-[120px] grid w-[1100px] max-w-xs grid-cols-[1fr] text-center',
          )}
        >
          <CardLink
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Docs"
            description="Find in-depth information about Next.js features and API."
          />

          <CardLink
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <CardLink
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Templates"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <CardLink
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy"
            description="Instantly deploy your Next.js site to a shareable URL with Vercel."
          />
        </div>
      </main>
    </>
  );
}
